### PR TITLE
feat: add bullets finance

### PR DESCRIPTION
**Pull request by BulletSwap-DEX**
adding bullets finance

### CODE REVIEW

**Comment by BulletSwap-DEX** [comment]
#LFG with Bullets Finance 🚀

**Comment by michael77-alt** [comment]
I think this is a hidden gem project, LFG 🚀

**Comment by saifulrhmn-afk** [comment]
#LFG Bullets Finance 🚀

**Comment by BulletSwap-DEX** [comment]
> #LFG Bullets Finance 🚀

Thanks for your support with our project :)

**Comment by saifulrhmn-afk** [comment]
LFG Gunners

**Comment by graemeblackwood** [comment]
Thanks for submitting this. We don't yet support zkSync dapps on dappland but are looking into it. We'll ping you when we've made progress.

**Comment by BulletSwap-DEX** [comment]
> Thanks for submitting this. We don't yet support zkSync dapps on dappland but are looking into it. We'll ping you when we've made progress.

Hmmb okkay mate, i'll waiting for a good news from you

**Pull request closed without merging**
