### PR TITLE
Create redline.json

### PR DESCRIPTION
**Pull request by shramee**
Added REDLINE game dapp.

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@shramee Thanks for this. Are you able to provide an SVG version of this? https://pbs.twimg.com/profile_images/1508168833768452096/m-BWCHn2_400x400.jpg

We've changed the structure of the assets a bit. Once I have that logo, I'll open a new PR with these changes and we'll merge that.

**Comment by shramee** [comment]
Hi @graemeblackwood,
I've added this to json,
https://redline.game/media/logo.png
img

Does this work?

**Comment by graemeblackwood** [comment]
@shramee yes that is fine, as long as you are happy with it being quite small: 

image

**Comment by shramee** [comment]
Thanks a lot for the preview @graemeblackwood. 😃

It does seem rather small, here's a squarish version. Updated in the PR :wink:
https://redline.game/media/logo-r-400.webp

Logo square

**Comment by graemeblackwood** [comment]
@shramee that works. I've created a new PR to replace this as we restructured the directory structure after you issues your PR. I'll close this one and we'll merge the other: #33

**Comment by shramee** [comment]
### Woop woop!! 🥳

**Pull request closed without merging**
