### PR TITLE
Add Pyramid Market

### PR DESCRIPTION
**Pull request by ahmetoznar**

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@ahmetoznar please add the gallery images to the repo too and adjust the references to them in your dapp JSON.

**Comment by ahmetoznar** [comment]
> 

I have added some photos from app. Please check.

**Comment by graemeblackwood** [comment]
@ahmetoznar I've fixed the broken build so technically able to merge now. The new screenshot image files (PNGs) are huge though. Could you convert these to jpg and compress using tinyjpg.com, please?

**Comment by ahmetoznar** [comment]
Okay, I compressed the images and updated json file, please check.

**Comment by selarun13** [comment]
0x6f99e90dd385c23826b416528e325214671febf6

**Pull request merged**
