### PR TITLE
feat: add dynamic.xyz dapp to dappland

### PR DESCRIPTION
**Pull request by paololim**

### CODE REVIEW

**Comment by turbahn** [comment]
@graemeblackwood hello! I just realized this was never merged. What are the next steps here?

Thanks!
Itai

**Comment by turbahn** [comment]
@graemeblackwood @janek26 quick ping on this. Thanks!!

**Comment by graemeblackwood** [comment]
@turbahn Apologies for the delay on this. We've been debating it a bit as the main idea behind Dappland is to showcase Dapps, but given we have an infrastructure category and it's stoll early days, we'll add dynamic until the dapp ecosystem itself grows and we can shift the focus more purely to dapps only.

Could you take a look at the latest data template, and update to that please? It's changed a fair bit since your original PR.

**Comment by paololim** [comment]
@graemeblackwood @turbahn I have updated the dynamic.json based on the newer example json. Let me know if anything else is missing or needs to be changed. Thanks!

**Comment by graemeblackwood** [comment]
Thanks!

**Pull request merged**
