### PR TITLE
Adding Haiko

### PR DESCRIPTION
**Pull request by parketh**

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@parketh Looks like you removed the mainnet contracts section of the data JSON file. Please check against another dapp to be sure it's all as it should be. I assume you're not on mainnet yet as the contracts are all Goerli?

**Comment by parketh** [comment]
Whoops - thanks for flagging, I've now added back the missing fields + fixed a typo

**Comment by graemeblackwood** [comment]
@parketh I've fixed the build for you – the JSON was missing the tokens field.

It looks like Haiko is Testnet only for now, though? So please let me know when you've gone to production and I'll merge.

**Comment by parketh** [comment]
Understood - we are planning for mainnet month end (31st Jan). If only production projects can be listed, I'll check back in at the end of the month here. 

Thanks for fixing the PR, and sorry for the back and forth!

**Comment by graemeblackwood** [comment]
@parketh Looks like you're live, albeit with limited liquidity?

**Comment by parketh** [comment]
Hey yes @graemeblackwood let me update the PR

**Comment by parketh** [comment]
@graemeblackwood I have added the mainnet contracts

**Comment by graemeblackwood** [comment]
Thanks!

**Pull request merged**
