### PR TITLE
rhinofi integration on dappland

### PR DESCRIPTION
**Pull request by nicob21**
PR containing all the info in the JSON file and the associated media to integrate rhino.fi on Dappland. Thanks

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@nicob21 thanks for this! Looks like you removed the verified status, and this is causing the build to break.

Please add back into the JSON, and if the contracts are verified on Starkscan, set this to true. Otherwise set as false.

**Comment by nicob21** [comment]
@graemeblackwood is everything good now?

**Comment by graemeblackwood** [comment]
@nicob21 The build is still broken. I tried to fix it for you but I can't push to the rhinofi-integration branch on your fork.

Please add   `"tokens": [],` back into the JSON. That will fix it, and I can then merge.

Thanks!

**Comment by nicob21** [comment]
@graemeblackwood added 👍

**Comment by graemeblackwood** [comment]
@nicob21 The build is ok now, but when using RhinoFi, I don't see any option to connect to a Starknet wallet? How does RhinoFi work with Starknet?

**Comment by graemeblackwood** [comment]
@nicob21 Ignore that – I've just gone through the full process. It is a bit confusing when I set Starknet -> Ethereum, and click the "Connect wallet" button, but it shows me Ethereum wallets.

I expected to see Starknet wallets first if I set the origin as Starknet.

Merging now.

**Pull request merged**
