### PR TITLE
feat: Rebranding Alpha Road to AVNU

### PR DESCRIPTION
**Pull request by florian-bellotti**

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@florian-bellotti Thanks for this.

Please:
- Add mainnet contracts (and set verified to true if they are all verified)
- If the contracts have been audited, please add a link to the report
- Shorten the `short_description` field. I suggest "Decentralized exchange protocol" or "Execution-optimised decentralized exchange"
- There are three assets needed. The original Alpha Road listing only used two, and reused the banner image for the preview. With the design you have shared, you'll need all three. Please have a look at this template for details: https://www.figma.com/community/file/1163928128813560560
- Would be great to have the founding date e.g. `2022-01-01T00:00:00.000Z`
- And you don't seem to be anonymous either, so feel free to set that to false.

**Comment by florian-bellotti** [comment]
> @florian-bellotti Thanks for this.
> 
> Please:
> 
>     * Add mainnet contracts (and set verified to true if they are all verified)
> 
>     * If the contracts have been audited, please add a link to the report
> 
>     * Shorten the `short_description` field. I suggest "Decentralized exchange protocol" or "Execution-optimised decentralized exchange"
> 
>     * There are three assets needed. The original Alpha Road listing only used two, and reused the banner image for the preview. With the design you have shared, you'll need all three. Please have a look at this template for details: https://www.figma.com/community/file/1163928128813560560
> 
>     * Would be great to have the founding date e.g. `2022-01-01T00:00:00.000Z`
> 
>     * And you don't seem to be anonymous either, so feel free to set that to false.

Done

**Comment by florian-bellotti** [comment]
@graemeblackwood done

**Comment by graemeblackwood** [comment]
@florian-bellotti Brilliant, thanks! Once you're ready, please do a new PR to add mainnet contracts (and set verified to true if you get them verified on Starkscan)

**Pull request merged**
