### PR TITLE
feat: add MorphineFi + StarkenFi

### PR DESCRIPTION
**Pull request by 0xSacha**

### CODE REVIEW

**Comment by 0xSacha** [comment]
@graemeblackwood sorry for the late answer! 
yes we have contracts deployed on Goerli 2, but not on mainnet :)

**Comment by graemeblackwood** [comment]
@0xSacha We're starting to only add mainnet dapps now, so please update with the mainnet contracts when you launch and I'll add immediately.

Also please run your images through an optimiser like tinyjpg.com

**Comment by 0xSacha** [comment]
@graemeblackwood Those 2 apps are doing analytics for now and running on mainnet. 
I pushed optimized images now, should be all good

**Comment by graemeblackwood** [comment]
Looks good, thanks!

**Pull request merged**
