### PR TITLE
add Carmine Finance

### PR DESCRIPTION
**Pull request by DaveVodrazka**

### CODE REVIEW

**Comment by DaveVodrazka** [comment]
Hi, we have a private channel on the Argent discord: https://discord.com/channels/598897994477207572/1032560357153181696

If you have any questions please let us know in this channel

**Comment by graemeblackwood** [comment]
@DaveVodrazka Thanks for this. Please update the data JSON to the name of your dapp, i.e. `carminefinance.json` and then move to the `/data` directory: https://github.com/argentlabs/dappland/tree/develop/data

**Comment by graemeblackwood** [comment]
@DaveVodrazka I can see it now. Please also set verified to true as I can see that your contracts are verified on Starkscan, which is great and something visitors can filter by.

I think that's the only thing left.

**Comment by DaveVodrazka** [comment]
@graemeblackwood thank you, nice catch 👍  I set it to true

**Comment by graemeblackwood** [comment]
@DaveVodrazka I just noticed that "audited" is set to true., but you haven't provided a link to the audit report. If you are happy to do this, please issue a new PR with the link included. If not, I'll set `audited` to false.

The format is 

```
"audits": [
  {
    "name": "Audit name",
    "url": "https://linktoreport/"
  }
],
```

Thanks!

**Comment by DaveVodrazka** [comment]
Hi, thanks for pointing that out!
We are audited, but the report has not been finalised yet. Please, set it to false and once the report is done I will create a PR updating it with the link.

**Pull request merged**
