### PR TITLE
Add Rango (rango.json and images)

### PR DESCRIPTION
**Pull request by georgelombardi97**

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@georgelombardi97 thanks for sharing this. Please include your Starknet contracts and whether they are verified or not.

**Comment by georgelombardi97** [comment]
> @georgelombardi97 thanks for sharing this. Please include your Starknet contracts and whether they are verified or not.

Hi @graemeblackwood . Thanks for reviewing. We are a dex and bridge aggregator and currently we don't have any router contracts ourselves yet. If we develop and deploy contracts on Starknet, I will add them. But currently we dont have contracts.

**Comment by graemeblackwood** [comment]
@georgelombardi97 Ok, understood. I just tried to use Rango to send from Starknet to Ethereum mainnet, and also to swap ETH to DAI on Starknet, but both showed "No routes found"

I'll merge this as you clearly support Starknet, but it would be good to know if you plan to provide routes for these actions.

**Comment by georgelombardi97** [comment]
> @georgelombardi97 Ok, understood. I just tried to use Rango to send from Starknet to Ethereum mainnet, and also to swap ETH to DAI on Starknet, but both showed "No routes found"
> 
> I'll merge this as you clearly support Starknet, but it would be good to know if you plan to provide routes for these actions.

Thank you very much for your consideration. Actually we provided routes couple of days ago but orbiter bridge has paused transfers to and from Starknet. Also our swapper integration has run into issues. Our team is working on both aspects.

**Comment by georgelombardi97** [comment]
> @georgelombardi97 Your text is being cropped in the header and preview image. I would avoid text in the preview image and ensure any text is kept inside the safe area for the banner.
> 
> Please also give your logo a solid background or make the logo smaller so that it fits correctly inside the circle.
> 
> You can use this as a guide: https://www.figma.com/community/file/1163928128813560560
> 
> image

Thanks for the info! I updated the images to reflect your comment.

**Review by graemeblackwood — APPROVED** [review]

**Pull request merged**
