### PR TITLE
Add teahouse dapp to dappland

### PR DESCRIPTION
**Pull request by Furxx2000**
Add:
teahousefinance.json 
teahousefinance-banner.png
teahousefinance-logo.png
teahousefinance-preview.png

### CODE REVIEW

**Comment by graemeblackwood** [comment]
@Furxx2000 Thanks for this. Please check the link to the audits. It's broken for me (permission denied)

**Comment by Furxx2000** [comment]
Thank you @graemeblackwood , but where is the link of the audits?, can you provide the link and I'll try to change the permission for you.

**Comment by graemeblackwood** [comment]
@Furxx2000 if you view the preview Vercel build, you can see how the Teahouse page is constructed, and that the Audits link is broken: https://dappland-git-fork-furxx2000-develop-argentlabs.vercel.app/teahousefinance

This comes from the JSON file, where you added the audit link.

**Comment by Furxx2000** [comment]
@graemeblackwood , thank you, the audit link has updated in the JSON file.

**Comment by graemeblackwood** [comment]
Merged, though your Discord link appears outdated, so you might want to fix that.

**Pull request merged**
