### PR TITLE
feat: update zklend img

### PR DESCRIPTION
**Pull request by pei-linear**
Added three images for zklend

### CODE REVIEW

**Comment by pei-zklend** [comment]
Hi there, any updates on this?

**Comment by graemeblackwood** [comment]
@pei-linear Thanks for these updates. Can you make the squared logo a bit smaller, please? Dappland crops this into a circle and at that size it will break the positioning and also look incorrect relatively to the other dapp icons. Best to use another icon or the original zkLend icon as a guide.

**Comment by peihaochan** [comment]
@graemeblackwood sure, let me get that done and put in another review. Thanks

**Comment by peihaochan** [comment]
@graemeblackwood sure, let me get that sorted and put in another review. Thanks

**Comment by pei-linear** [comment]
@graemeblackwood  sure, let me get that sorted and put in another review. Thanks

**Review by pei-linear — COMMENTED** [review]
@graemeblackwood  
New logo updated. Let me know if you have any issues

**Comment by pei-linear** [comment]
Hello @graemeblackwood, just a quick follow up on this. Thanks!

**Comment by graemeblackwood** [comment]
Looks good, thanks!

**Pull request merged**
