### PR TITLE
add protoss dex

### PR DESCRIPTION
**Pull request by protoss-star**

### CODE REVIEW

**Comment by protoss-star** [comment]
Any updates?

**Comment by graemeblackwood** [comment]
@protoss-star I'm waiting on the image optimisations. The file sizes are too large currently. Please convert the two banners to JPG and run through tinyjpg.com

Also please run the logo through tinypng.com

**Comment by helix-blox** [comment]
> @protoss-star I'm waiting on the image optimisations. The file sizes are too large currently. Please convert the two banners to JPG and run through tinyjpg.com
> 
> Also please run the logo through tinypng.com
> 
> Lastly, please update "verified": false, to true, as your contracts are verified on Starkscan.

sure I already updated them.

**Comment by protoss-star** [comment]
> @protoss-star I'm waiting on the image optimisations. The file sizes are too large currently. Please convert the two banners to JPG and run through tinyjpg.com
> 
> Also please run the logo through tinypng.com
> 
> Lastly, please update "verified": false, to true, as your contracts are verified on Starkscan.

Thanks for the suggestion, I fixed those issues. Please check again, thanks a lot.

**Comment by graemeblackwood** [comment]
@protoss-star Easiest to get this merged is for you to allow me to push to your fork. It's resitricted at the moment. Alternatively please check the comments above to see what's left (just removing the yarn.lock and using an optimised .png for the logo image only)

**Pull request merged**
